#!/usr/bin/python

import dbus
import json
import os
from gi.repository import GObject, Gtk
from gi.repository import AppIndicator3 as appindicator
from dbus import glib
from dbus.mainloop.glib import DBusGMainLoop
glib.init_threads()

class IndicatorDeskCon:
    def __init__(self):
        workingdir = os.getcwd()

        self.ind = appindicator.Indicator.new("indicator-deskcon", 
                            workingdir+"/indicator-deskcon.svg",
                            appindicator.IndicatorCategory.APPLICATION_STATUS)

        self.ind.set_status (appindicator.IndicatorStatus.ACTIVE)

        self.menu = Gtk.Menu()

        self.menu.show()
        self.ind.set_menu(self.menu)
        self.dbusclient = DbusClient(self)
        self.devicelist = {}

        #Settings Button
        self.settingsitem = Gtk.MenuItem("Settings")
        self.settingsitem.connect("activate", self.showsettings)
        self.settingsitem.show()
        self.menu.append(self.settingsitem)
        #Setup Button
        self.setupdeviceitem = Gtk.MenuItem("Setup Device")
        self.setupdeviceitem.connect("activate", self.setupdevice)
        self.setupdeviceitem.show()
        self.menu.append(self.setupdeviceitem)
    
    def update(self):
        try:
            jsonstr = self.dbusclient.getStats()
        except Exception:
            jsonstr = "{}"
        data = json.loads(jsonstr)

        if (not data.has_key('phones')):
            return
        devices = data['phones']

        for device in devices:
            uuid = device['uuid']
            if (self.devicelist.has_key(uuid)):
                self.devicelist[uuid].update(device)
            else:
                newdevice = DeviceMenuBundle(self, device)
                self.devicelist[uuid] = newdevice

    def notificationhandler(self):
        notification = self.dbusclient.getNotifications().split('::')
        uuid = notification[0]
        text = notification[1]

        if (self.devicelist.has_key(uuid)):
            self.devicelist[uuid].addnotification(text)
        else:
            self.update()
            self.devicelist[uuid].addnotification(text)      

    
    def handler_menu_exit(self, evt):
        Gtk.main_quit()

    def compose(self, evt, ip, port):
        self.dbusclient.compose(ip, port)

    def ping(self, evt, ip, port):
        self.dbusclient.ping(ip, port)

    def sendfile(self, evt, ip, port):
        self.dbusclient.send_file(ip, port)

    def showsettings(self, evt):
        self.dbusclient.show_settings()

    def setupdevice(self, evt):
        self.dbusclient.setup_device()

    def main(self):
        self.dbusclient.run()
        self.update()
        Gtk.main()

class DeviceMenuBundle():
    def __init__(self, indicator, data):
        self.indicator = indicator 

        self.statsitem = Gtk.MenuItem("")
        self.statsitem.show()
        self.actionmenu = Gtk.Menu()
        self.statsitem.set_submenu(self.actionmenu)
        self.indicator.menu.insert(self.statsitem, 0)  
        self.composeitem = None

        #Actions
        if (data['canmessage']):
            self.composeitem = Gtk.MenuItem("Compose Message ...")
            self.composeitem.connect("activate", self.indicator.compose, 
                            data['ip'], data['controlport'])
            self.composeitem.show()
            self.actionmenu.append(self.composeitem)

        self.pingitem = Gtk.MenuItem("Ping")
        self.pingitem.connect("activate", self.indicator.ping, 
                        data['ip'], data['controlport'])
        self.pingitem.show()
        self.actionmenu.append(self.pingitem)

        self.sendfileitem = Gtk.MenuItem("Send File(s)")
        self.sendfileitem.connect("activate", self.indicator.sendfile, 
                        data['ip'], data['controlport'])
        self.sendfileitem.show()
        self.actionmenu.append(self.sendfileitem)
        
        #Notifications
        self.notificationlist = []
        self.notificationitem = Gtk.MenuItem("Notifications")
        self.notificationsmenu = Gtk.Menu()
        self.notificationitem.set_submenu(self.notificationsmenu)
        self.notclearitem = Gtk.MenuItem("clear")
        self.notclearitem.connect("activate", self.clearnotifications)
        self.notclearitem.show()
        separator = Gtk.SeparatorMenuItem()
        separator.show()
        self.notificationsmenu.append(separator)
        self.notificationsmenu.append(self.notclearitem)

        separator = Gtk.SeparatorMenuItem()
        separator.show()
        self.indicator.menu.insert(self.notificationitem, 1)
        #Sep
        self.indicator.menu.insert(separator, 2)

        self.update(data)

    def update(self, data):
        name = data['name']
        volume = str(data['volume'])
        battery = str(data['battery'])
        storage = str(data['storage'])
        missedsmstxt = ""
        missedcalltxt = ""
        if (data['missedsmscount'] > 0): 
            missedsmstxt = "\nunread Messages "+ str(data['missedsmscount'])     
        if (data['missedcallcount'] > 0): 
            missedcalltxt = "\nmissed Calls "+ str(data['missedcallcount'])
        missedtxt = missedsmstxt+missedcalltxt
        
        text = (name+
                "\nBat: "+battery+"% / Vol: "+volume+"% / Str: "+storage+"%"+
                missedtxt)

        self.statsitem.set_label(text)
        if (data['canmessage'] and self.composeitem == None):
            self.composeitem = Gtk.MenuItem("Compose Message ...")
            self.composeitem.connect("activate", self.indicator.compose, 
                            data['ip'], data['controlport'])
            self.composeitem.show()
            self.actionmenu.append(self.composeitem)

    def addnotification(self, text):
        notificationitem = Gtk.MenuItem(text)
        notificationitem.show()
        self.notificationlist.append(notificationitem)
        self.notificationsmenu.insert(notificationitem, 0)
        self.notificationitem.show()

    def clearnotifications(self, widget):
        for item in self.notificationlist:
            self.notificationlist.remove(item)
            item.destroy()
        self.notificationitem.hide()

    # get pos child poc in menu
    def getmenuposition(self):
        pos = 0
        for child in self.indicator.menu.get_children():
            if (child == self.statsitem):
                return pos
            pos = pos + 1


class DbusClient():
    def __init__(self, indicator):
        self.indicator = indicator
        bus = dbus.SessionBus()
        try:
            proxy = bus.get_object("net.screenfreeze.desktopconnector",
                                   "/net/screenfreeze/desktopconnector",
                                   True, True)
            self.iface = dbus.Interface(proxy, 'net.screenfreeze.desktopconnector')
        except Exception:
            print "dbus error"
       
        bus.add_signal_receiver(self.indicator.update,
                        dbus_interface="net.screenfreeze.desktopconnector",
                        signal_name="changed")
        bus.add_signal_receiver(self.indicator.notificationhandler,
                        dbus_interface="net.screenfreeze.desktopconnector",
                        signal_name="new_notification")

    def run(self):
        DBusGMainLoop(set_as_default=True)        
        GObject.threads_init()
        dbus.mainloop.glib.threads_init()

    def getStats(self):
        return self.iface.stats()

    def getNotifications(self):
        return self.iface.notification()

    def compose(self, ip, port):
        host = ip + ":" + str(port)
        self.iface.compose_sms(host)

    def ping(self, ip, port):
        host = ip + ":" + str(port)
        self.iface.ping_device(host)

    def send_file(self, ip, port):
        host = ip + ":" + str(port)
        self.iface.send_file(host)

    def show_settings(self):
        self.iface.show_settings()

    def setup_device(self):
        self.iface.setup_device()


if __name__ == "__main__":
    ind = IndicatorDeskCon()
    ind.main()
